name: ci

on:
  push:
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -G Ninja -B b
      - run: cmake --build b

  linux:
    runs-on: linux-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake -G Ninja -B b
      - run: cmake --build b
